/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AcceptedResponse
 */
@JsonPropertyOrder({
  AcceptedResponse.JSON_PROPERTY_MESSAGE_ID,
  AcceptedResponse.JSON_PROPERTY_STATUS,
  AcceptedResponse.JSON_PROPERTY_SERVER_STARTED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-26T13:12:30.193024900+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class AcceptedResponse {
  public static final String JSON_PROPERTY_MESSAGE_ID = "messageId";
  @jakarta.annotation.Nonnull
  private UUID messageId;

  /**
   * The Server has durably taken ownership of the message.
   */
  public enum StatusEnum {
    ACCEPTED(String.valueOf("accepted"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_SERVER_STARTED_AT = "serverStartedAt";
  @jakarta.annotation.Nullable
  private Long serverStartedAt;

  public AcceptedResponse() {
  }

  public AcceptedResponse messageId(@jakarta.annotation.Nonnull UUID messageId) {
    
    this.messageId = messageId;
    return this;
  }

  /**
   * ID of the accepted message (echoed from the request).
   * @return messageId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getMessageId() {
    return messageId;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageId(@jakarta.annotation.Nonnull UUID messageId) {
    this.messageId = messageId;
  }

  public AcceptedResponse status(@jakarta.annotation.Nonnull StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * The Server has durably taken ownership of the message.
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }

  public AcceptedResponse serverStartedAt(@jakarta.annotation.Nullable Long serverStartedAt) {
    
    this.serverStartedAt = serverStartedAt;
    return this;
  }

  /**
   * Epoch milliseconds at which this Server process started. A changed value across responses signals a restart, after which the client re-submits its unconfirmed outbox messages.
   * @return serverStartedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVER_STARTED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getServerStartedAt() {
    return serverStartedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVER_STARTED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServerStartedAt(@jakarta.annotation.Nullable Long serverStartedAt) {
    this.serverStartedAt = serverStartedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AcceptedResponse acceptedResponse = (AcceptedResponse) o;
    return Objects.equals(this.messageId, acceptedResponse.messageId) &&
        Objects.equals(this.status, acceptedResponse.status) &&
        Objects.equals(this.serverStartedAt, acceptedResponse.serverStartedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageId, status, serverStartedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AcceptedResponse {\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    serverStartedAt: ").append(toIndentedString(serverStartedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

