/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Client -&gt; Hub: an ephemeral call signal (ringing, answer, ICE candidates, hangup, decline, busy) for a 1:1 call.
 */
@JsonPropertyOrder({
  CallSignalCommand.JSON_PROPERTY_TYPE,
  CallSignalCommand.JSON_PROPERTY_RECIPIENT_ID,
  CallSignalCommand.JSON_PROPERTY_PAYLOAD
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class CallSignalCommand {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    CALL_SIGNAL(String.valueOf("call_signal"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_RECIPIENT_ID = "recipientId";
  @jakarta.annotation.Nonnull
  private UUID recipientId;

  public static final String JSON_PROPERTY_PAYLOAD = "payload";
  @jakarta.annotation.Nonnull
  private String payload;

  public CallSignalCommand() {
  }

  public CallSignalCommand type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public CallSignalCommand recipientId(@jakarta.annotation.Nonnull UUID recipientId) {
    
    this.recipientId = recipientId;
    return this;
  }

  /**
   * The call peer this signal is addressed to.
   * @return recipientId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECIPIENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getRecipientId() {
    return recipientId;
  }


  @JsonProperty(value = JSON_PROPERTY_RECIPIENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecipientId(@jakarta.annotation.Nonnull UUID recipientId) {
    this.recipientId = recipientId;
  }

  public CallSignalCommand payload(@jakarta.annotation.Nonnull String payload) {
    
    this.payload = payload;
    return this;
  }

  /**
   * E2E encrypted call signal over the pairwise Double Ratchet. Format &#39;&lt;sessionType&gt;.&lt;bodyBase64&gt;&#39;, as for a 1:1 EncryptedMessage payload.
   * @return payload
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYLOAD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPayload() {
    return payload;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYLOAD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayload(@jakarta.annotation.Nonnull String payload) {
    this.payload = payload;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallSignalCommand callSignalCommand = (CallSignalCommand) o;
    return Objects.equals(this.type, callSignalCommand.type) &&
        Objects.equals(this.recipientId, callSignalCommand.recipientId) &&
        Objects.equals(this.payload, callSignalCommand.payload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, recipientId, payload);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallSignalCommand {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    recipientId: ").append(toIndentedString(recipientId)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

