/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Hub -&gt; client: an ephemeral call signal from a call peer.
 */
@JsonPropertyOrder({
  CallSignalEvent.JSON_PROPERTY_TYPE,
  CallSignalEvent.JSON_PROPERTY_SENDER_ID,
  CallSignalEvent.JSON_PROPERTY_PAYLOAD
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class CallSignalEvent {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    CALL_SIGNAL(String.valueOf("call_signal"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_SENDER_ID = "senderId";
  @jakarta.annotation.Nonnull
  private UUID senderId;

  public static final String JSON_PROPERTY_PAYLOAD = "payload";
  @jakarta.annotation.Nonnull
  private String payload;

  public CallSignalEvent() {
  }

  public CallSignalEvent type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public CallSignalEvent senderId(@jakarta.annotation.Nonnull UUID senderId) {
    
    this.senderId = senderId;
    return this;
  }

  /**
   * The call peer that sent the signal, stamped by the sender&#39;s Hub from its authenticated session.
   * @return senderId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SENDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getSenderId() {
    return senderId;
  }


  @JsonProperty(value = JSON_PROPERTY_SENDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSenderId(@jakarta.annotation.Nonnull UUID senderId) {
    this.senderId = senderId;
  }

  public CallSignalEvent payload(@jakarta.annotation.Nonnull String payload) {
    
    this.payload = payload;
    return this;
  }

  /**
   * E2E encrypted call signal, relayed unaltered from the CallSignalCommand.
   * @return payload
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYLOAD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPayload() {
    return payload;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYLOAD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayload(@jakarta.annotation.Nonnull String payload) {
    this.payload = payload;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallSignalEvent callSignalEvent = (CallSignalEvent) o;
    return Objects.equals(this.type, callSignalEvent.type) &&
        Objects.equals(this.senderId, callSignalEvent.senderId) &&
        Objects.equals(this.payload, callSignalEvent.payload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, senderId, payload);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallSignalEvent {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    senderId: ").append(toIndentedString(senderId)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

