/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import net.fourletters.dto.WrappedGroupKey;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Creates a group with the caller as owner and an initial epoch-0 key set wrapped to every member.
 */
@JsonPropertyOrder({
  CreateGroupRequest.JSON_PROPERTY_NAME,
  CreateGroupRequest.JSON_PROPERTY_MEMBERS,
  CreateGroupRequest.JSON_PROPERTY_KEYS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-22T14:10:45.096494+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class CreateGroupRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_MEMBERS = "members";
  @jakarta.annotation.Nonnull
  private List<UUID> members = new ArrayList<>();

  public static final String JSON_PROPERTY_KEYS = "keys";
  @jakarta.annotation.Nonnull
  private List<WrappedGroupKey> keys = new ArrayList<>();

  public CreateGroupRequest() {
  }

  public CreateGroupRequest name(@jakarta.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Group name (plaintext).
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public CreateGroupRequest members(@jakarta.annotation.Nonnull List<UUID> members) {
    
    this.members = members;
    return this;
  }

  public CreateGroupRequest addMembersItem(UUID membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<>();
    }
    this.members.add(membersItem);
    return this;
  }

  /**
   * Initial member user ids (the owner is added automatically if omitted).
   * @return members
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MEMBERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<UUID> getMembers() {
    return members;
  }


  @JsonProperty(value = JSON_PROPERTY_MEMBERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMembers(@jakarta.annotation.Nonnull List<UUID> members) {
    this.members = members;
  }

  public CreateGroupRequest keys(@jakarta.annotation.Nonnull List<WrappedGroupKey> keys) {
    
    this.keys = keys;
    return this;
  }

  public CreateGroupRequest addKeysItem(WrappedGroupKey keysItem) {
    if (this.keys == null) {
      this.keys = new ArrayList<>();
    }
    this.keys.add(keysItem);
    return this;
  }

  /**
   * Epoch-0 group key wrapped to every initial member (including the owner).
   * @return keys
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<WrappedGroupKey> getKeys() {
    return keys;
  }


  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeys(@jakarta.annotation.Nonnull List<WrappedGroupKey> keys) {
    this.keys = keys;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateGroupRequest createGroupRequest = (CreateGroupRequest) o;
    return Objects.equals(this.name, createGroupRequest.name) &&
        Objects.equals(this.members, createGroupRequest.members) &&
        Objects.equals(this.keys, createGroupRequest.keys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, members, keys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateGroupRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

