/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import net.fourletters.dto.ReceiptType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DeliveryReceipt
 */
@JsonPropertyOrder({
  DeliveryReceipt.JSON_PROPERTY_MESSAGE_ID,
  DeliveryReceipt.JSON_PROPERTY_ORIGINAL_SENDER_ID,
  DeliveryReceipt.JSON_PROPERTY_TYPE,
  DeliveryReceipt.JSON_PROPERTY_SIGNATURE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-16T11:55:01.971963700+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class DeliveryReceipt {
  public static final String JSON_PROPERTY_MESSAGE_ID = "messageId";
  @jakarta.annotation.Nonnull
  private UUID messageId;

  public static final String JSON_PROPERTY_ORIGINAL_SENDER_ID = "originalSenderId";
  @jakarta.annotation.Nullable
  private UUID originalSenderId;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private ReceiptType type;

  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  @jakarta.annotation.Nonnull
  private String signature;

  public DeliveryReceipt() {
  }

  public DeliveryReceipt messageId(@jakarta.annotation.Nonnull UUID messageId) {
    
    this.messageId = messageId;
    return this;
  }

  /**
   * ID of the message being acknowledged.
   * @return messageId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getMessageId() {
    return messageId;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageId(@jakarta.annotation.Nonnull UUID messageId) {
    this.messageId = messageId;
  }

  public DeliveryReceipt originalSenderId(@jakarta.annotation.Nullable UUID originalSenderId) {
    
    this.originalSenderId = originalSenderId;
    return this;
  }

  /**
   * ID of the original message&#39;s sender — the party to notify. Echoed by the recipient from the received message so the Server can relay this receipt 
   * @return originalSenderId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORIGINAL_SENDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getOriginalSenderId() {
    return originalSenderId;
  }


  @JsonProperty(value = JSON_PROPERTY_ORIGINAL_SENDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOriginalSenderId(@jakarta.annotation.Nullable UUID originalSenderId) {
    this.originalSenderId = originalSenderId;
  }

  public DeliveryReceipt type(@jakarta.annotation.Nonnull ReceiptType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ReceiptType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull ReceiptType type) {
    this.type = type;
  }

  public DeliveryReceipt signature(@jakarta.annotation.Nonnull String signature) {
    
    this.signature = signature;
    return this;
  }

  /**
   * Signature over (messageId, type, originalSenderId) by the recipient&#39;s identity key (Base64). Lets the original sender trust the receipt without trusting any Hub.
   * @return signature
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SIGNATURE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignature() {
    return signature;
  }


  @JsonProperty(value = JSON_PROPERTY_SIGNATURE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignature(@jakarta.annotation.Nonnull String signature) {
    this.signature = signature;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryReceipt deliveryReceipt = (DeliveryReceipt) o;
    return Objects.equals(this.messageId, deliveryReceipt.messageId) &&
        Objects.equals(this.originalSenderId, deliveryReceipt.originalSenderId) &&
        Objects.equals(this.type, deliveryReceipt.type) &&
        Objects.equals(this.signature, deliveryReceipt.signature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageId, originalSenderId, type, signature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryReceipt {\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    originalSenderId: ").append(toIndentedString(originalSenderId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

