/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EncryptedMessage
 */
@JsonPropertyOrder({
  EncryptedMessage.JSON_PROPERTY_MESSAGE_ID,
  EncryptedMessage.JSON_PROPERTY_RECIPIENT_ID,
  EncryptedMessage.JSON_PROPERTY_SENDER_ID,
  EncryptedMessage.JSON_PROPERTY_PAYLOAD,
  EncryptedMessage.JSON_PROPERTY_GROUP_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-08T13:45:24.988885800+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class EncryptedMessage {
  public static final String JSON_PROPERTY_MESSAGE_ID = "messageId";
  @jakarta.annotation.Nonnull
  private UUID messageId;

  public static final String JSON_PROPERTY_RECIPIENT_ID = "recipientId";
  @jakarta.annotation.Nonnull
  private UUID recipientId;

  public static final String JSON_PROPERTY_SENDER_ID = "senderId";
  @jakarta.annotation.Nullable
  private UUID senderId;

  public static final String JSON_PROPERTY_PAYLOAD = "payload";
  @jakarta.annotation.Nonnull
  private String payload;

  public static final String JSON_PROPERTY_GROUP_ID = "groupId";
  @jakarta.annotation.Nullable
  private UUID groupId;

  public EncryptedMessage() {
  }

  public EncryptedMessage messageId(@jakarta.annotation.Nonnull UUID messageId) {
    
    this.messageId = messageId;
    return this;
  }

  /**
   * Unique identifier for the message generated by the client
   * @return messageId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getMessageId() {
    return messageId;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageId(@jakarta.annotation.Nonnull UUID messageId) {
    this.messageId = messageId;
  }

  public EncryptedMessage recipientId(@jakarta.annotation.Nonnull UUID recipientId) {
    
    this.recipientId = recipientId;
    return this;
  }

  /**
   * ID of the recipient user
   * @return recipientId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECIPIENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getRecipientId() {
    return recipientId;
  }


  @JsonProperty(value = JSON_PROPERTY_RECIPIENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecipientId(@jakarta.annotation.Nonnull UUID recipientId) {
    this.recipientId = recipientId;
  }

  public EncryptedMessage senderId(@jakarta.annotation.Nullable UUID senderId) {
    
    this.senderId = senderId;
    return this;
  }

  /**
   * ID of the sender user. Set by the Server from the authenticated session at send time; any client-provided value is ignored. Omitted in the send request.
   * @return senderId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SENDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getSenderId() {
    return senderId;
  }


  @JsonProperty(value = JSON_PROPERTY_SENDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSenderId(@jakarta.annotation.Nullable UUID senderId) {
    this.senderId = senderId;
  }

  public EncryptedMessage payload(@jakarta.annotation.Nonnull String payload) {
    
    this.payload = payload;
    return this;
  }

  /**
   * E2E encrypted Signal ciphertext. Format &#39;&lt;sessionType&gt;.&lt;bodyBase64&gt;&#39; where sessionType is 1 (WhisperMessage, established session) or 3 (PreKeyWhisperMessage, establishes the session). The Server treats it as opaque.
   * @return payload
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYLOAD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPayload() {
    return payload;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYLOAD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayload(@jakarta.annotation.Nonnull String payload) {
    this.payload = payload;
  }

  public EncryptedMessage groupId(@jakarta.annotation.Nullable UUID groupId) {
    
    this.groupId = groupId;
    return this;
  }

  /**
   * Present only for group messages. Identifies the group so the recipient threads the message into the group conversation. The sender encrypts and sends one independent 1:1 copy per member; the Server treats each copy as an ordinary 1:1 message. Omitted for 1:1 messages.
   * @return groupId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GROUP_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getGroupId() {
    return groupId;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupId(@jakarta.annotation.Nullable UUID groupId) {
    this.groupId = groupId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EncryptedMessage encryptedMessage = (EncryptedMessage) o;
    return Objects.equals(this.messageId, encryptedMessage.messageId) &&
        Objects.equals(this.recipientId, encryptedMessage.recipientId) &&
        Objects.equals(this.senderId, encryptedMessage.senderId) &&
        Objects.equals(this.payload, encryptedMessage.payload) &&
        Objects.equals(this.groupId, encryptedMessage.groupId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageId, recipientId, senderId, payload, groupId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EncryptedMessage {\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    recipientId: ").append(toIndentedString(recipientId)).append("\n");
    sb.append("    senderId: ").append(toIndentedString(senderId)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

