/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Payload of a groupKeyRotated WS event.
 */
@JsonPropertyOrder({
  GroupKeyNotification.JSON_PROPERTY_GROUP_ID,
  GroupKeyNotification.JSON_PROPERTY_EPOCH
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-22T14:10:45.096494+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class GroupKeyNotification {
  public static final String JSON_PROPERTY_GROUP_ID = "groupId";
  @jakarta.annotation.Nonnull
  private UUID groupId;

  public static final String JSON_PROPERTY_EPOCH = "epoch";
  @jakarta.annotation.Nonnull
  private Long epoch;

  public GroupKeyNotification() {
  }

  public GroupKeyNotification groupId(@jakarta.annotation.Nonnull UUID groupId) {
    
    this.groupId = groupId;
    return this;
  }

  /**
   * The group whose key rotated.
   * @return groupId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_GROUP_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getGroupId() {
    return groupId;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGroupId(@jakarta.annotation.Nonnull UUID groupId) {
    this.groupId = groupId;
  }

  public GroupKeyNotification epoch(@jakarta.annotation.Nonnull Long epoch) {
    
    this.epoch = epoch;
    return this;
  }

  /**
   * The new current epoch.
   * @return epoch
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EPOCH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getEpoch() {
    return epoch;
  }


  @JsonProperty(value = JSON_PROPERTY_EPOCH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEpoch(@jakarta.annotation.Nonnull Long epoch) {
    this.epoch = epoch;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupKeyNotification groupKeyNotification = (GroupKeyNotification) o;
    return Objects.equals(this.groupId, groupKeyNotification.groupId) &&
        Objects.equals(this.epoch, groupKeyNotification.epoch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupId, epoch);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupKeyNotification {\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    epoch: ").append(toIndentedString(epoch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

