/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.fourletters.dto.WrappedGroupKey;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A complete set of wrapped group keys for one epoch, one entry per member. Generated client-side on create/rotation and posted to the Server, which relays the blobs and advances the roster epoch (compare-and-swap).
 */
@JsonPropertyOrder({
  GroupKeyDistribution.JSON_PROPERTY_EPOCH,
  GroupKeyDistribution.JSON_PROPERTY_KEYS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-22T14:10:45.096494+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class GroupKeyDistribution {
  public static final String JSON_PROPERTY_EPOCH = "epoch";
  @jakarta.annotation.Nonnull
  private Long epoch;

  public static final String JSON_PROPERTY_KEYS = "keys";
  @jakarta.annotation.Nonnull
  private List<WrappedGroupKey> keys = new ArrayList<>();

  public GroupKeyDistribution() {
  }

  public GroupKeyDistribution epoch(@jakarta.annotation.Nonnull Long epoch) {
    
    this.epoch = epoch;
    return this;
  }

  /**
   * The epoch these wrapped keys belong to. On rotation this must equal the group&#39;s current epoch + 1; the write is rejected (409) if the current epoch is not exactly the prior value.
   * @return epoch
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EPOCH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getEpoch() {
    return epoch;
  }


  @JsonProperty(value = JSON_PROPERTY_EPOCH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEpoch(@jakarta.annotation.Nonnull Long epoch) {
    this.epoch = epoch;
  }

  public GroupKeyDistribution keys(@jakarta.annotation.Nonnull List<WrappedGroupKey> keys) {
    
    this.keys = keys;
    return this;
  }

  public GroupKeyDistribution addKeysItem(WrappedGroupKey keysItem) {
    if (this.keys == null) {
      this.keys = new ArrayList<>();
    }
    this.keys.add(keysItem);
    return this;
  }

  /**
   * One wrapped key per member of the (post-change) roster. The Server validates the set covers exactly the roster.
   * @return keys
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<WrappedGroupKey> getKeys() {
    return keys;
  }


  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeys(@jakarta.annotation.Nonnull List<WrappedGroupKey> keys) {
    this.keys = keys;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupKeyDistribution groupKeyDistribution = (GroupKeyDistribution) o;
    return Objects.equals(this.epoch, groupKeyDistribution.epoch) &&
        Objects.equals(this.keys, groupKeyDistribution.keys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(epoch, keys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupKeyDistribution {\n");
    sb.append("    epoch: ").append(toIndentedString(epoch)).append("\n");
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

