/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import net.fourletters.dto.GroupMember;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A group conversation. The Server owns the roster; messages are sent as one independent 1:1 copy per member, so the Server never holds any group key material.
 */
@JsonPropertyOrder({
  Group.JSON_PROPERTY_ID,
  Group.JSON_PROPERTY_NAME,
  Group.JSON_PROPERTY_OWNER_ID,
  Group.JSON_PROPERTY_MEMBERS,
  Group.JSON_PROPERTY_CREATED_AT,
  Group.JSON_PROPERTY_UPDATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-06T15:05:45.914087500+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class Group {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_OWNER_ID = "ownerId";
  @jakarta.annotation.Nonnull
  private UUID ownerId;

  public static final String JSON_PROPERTY_MEMBERS = "members";
  @jakarta.annotation.Nonnull
  private List<GroupMember> members = new ArrayList<>();

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nullable
  private Long createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private Long updatedAt;

  public Group() {
  }

  public Group id(@jakarta.annotation.Nonnull UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Server-assigned group identifier.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }

  public Group name(@jakarta.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Human-readable group name (stored in plaintext server-side).
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public Group ownerId(@jakarta.annotation.Nonnull UUID ownerId) {
    
    this.ownerId = ownerId;
    return this;
  }

  /**
   * The group owner — the sole party permitted to change the roster.
   * @return ownerId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OWNER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getOwnerId() {
    return ownerId;
  }


  @JsonProperty(value = JSON_PROPERTY_OWNER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOwnerId(@jakarta.annotation.Nonnull UUID ownerId) {
    this.ownerId = ownerId;
  }

  public Group members(@jakarta.annotation.Nonnull List<GroupMember> members) {
    
    this.members = members;
    return this;
  }

  public Group addMembersItem(GroupMember membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<>();
    }
    this.members.add(membersItem);
    return this;
  }

  /**
   * The current roster.
   * @return members
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MEMBERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<GroupMember> getMembers() {
    return members;
  }


  @JsonProperty(value = JSON_PROPERTY_MEMBERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMembers(@jakarta.annotation.Nonnull List<GroupMember> members) {
    this.members = members;
  }

  public Group createdAt(@jakarta.annotation.Nullable Long createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Epoch milliseconds when the group was created.
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable Long createdAt) {
    this.createdAt = createdAt;
  }

  public Group updatedAt(@jakarta.annotation.Nullable Long updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Epoch milliseconds of the last roster change.
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable Long updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Group group = (Group) o;
    return Objects.equals(this.id, group.id) &&
        Objects.equals(this.name, group.name) &&
        Objects.equals(this.ownerId, group.ownerId) &&
        Objects.equals(this.members, group.members) &&
        Objects.equals(this.createdAt, group.createdAt) &&
        Objects.equals(this.updatedAt, group.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, ownerId, members, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Group {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

