/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A single member&#39;s wrapped group key for one epoch — what the caller pulls to obtain a key it is missing.
 */
@JsonPropertyOrder({
  GroupKeySet.JSON_PROPERTY_GROUP_ID,
  GroupKeySet.JSON_PROPERTY_EPOCH,
  GroupKeySet.JSON_PROPERTY_WRAPPED_KEY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-22T14:10:45.096494+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class GroupKeySet {
  public static final String JSON_PROPERTY_GROUP_ID = "groupId";
  @jakarta.annotation.Nonnull
  private UUID groupId;

  public static final String JSON_PROPERTY_EPOCH = "epoch";
  @jakarta.annotation.Nonnull
  private Long epoch;

  public static final String JSON_PROPERTY_WRAPPED_KEY = "wrappedKey";
  @jakarta.annotation.Nonnull
  private String wrappedKey;

  public GroupKeySet() {
  }

  public GroupKeySet groupId(@jakarta.annotation.Nonnull UUID groupId) {
    
    this.groupId = groupId;
    return this;
  }

  /**
   * The group this key belongs to.
   * @return groupId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_GROUP_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getGroupId() {
    return groupId;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGroupId(@jakarta.annotation.Nonnull UUID groupId) {
    this.groupId = groupId;
  }

  public GroupKeySet epoch(@jakarta.annotation.Nonnull Long epoch) {
    
    this.epoch = epoch;
    return this;
  }

  /**
   * The epoch this wrapped key is for.
   * @return epoch
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EPOCH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getEpoch() {
    return epoch;
  }


  @JsonProperty(value = JSON_PROPERTY_EPOCH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEpoch(@jakarta.annotation.Nonnull Long epoch) {
    this.epoch = epoch;
  }

  public GroupKeySet wrappedKey(@jakarta.annotation.Nonnull String wrappedKey) {
    
    this.wrappedKey = wrappedKey;
    return this;
  }

  /**
   * The group epoch key wrapped to the caller&#39;s encryption key (Base64).
   * @return wrappedKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WRAPPED_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWrappedKey() {
    return wrappedKey;
  }


  @JsonProperty(value = JSON_PROPERTY_WRAPPED_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWrappedKey(@jakarta.annotation.Nonnull String wrappedKey) {
    this.wrappedKey = wrappedKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupKeySet groupKeySet = (GroupKeySet) o;
    return Objects.equals(this.groupId, groupKeySet.groupId) &&
        Objects.equals(this.epoch, groupKeySet.epoch) &&
        Objects.equals(this.wrappedKey, groupKeySet.wrappedKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupId, epoch, wrappedKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupKeySet {\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    epoch: ").append(toIndentedString(epoch)).append("\n");
    sb.append("    wrappedKey: ").append(toIndentedString(wrappedKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

