/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * HubRegistrationResponse
 */
@JsonPropertyOrder({
  HubRegistrationResponse.JSON_PROPERTY_HUB_ID,
  HubRegistrationResponse.JSON_PROPERTY_QUEUE_NAME,
  HubRegistrationResponse.JSON_PROPERTY_EXCHANGE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-18T14:27:10.653535500+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class HubRegistrationResponse {
  public static final String JSON_PROPERTY_HUB_ID = "hubId";
  @jakarta.annotation.Nonnull
  private String hubId;

  public static final String JSON_PROPERTY_QUEUE_NAME = "queueName";
  @jakarta.annotation.Nonnull
  private String queueName;

  public static final String JSON_PROPERTY_EXCHANGE = "exchange";
  @jakarta.annotation.Nonnull
  private String exchange;

  public HubRegistrationResponse() {
  }

  public HubRegistrationResponse hubId(@jakarta.annotation.Nonnull String hubId) {
    
    this.hubId = hubId;
    return this;
  }

  /**
   * Server-assigned identifier for this Hub registration. Names the Hub&#39;s queue and (in the volunteer phase) ties it to an owner for accountability and revocation.
   * @return hubId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HUB_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getHubId() {
    return hubId;
  }


  @JsonProperty(value = JSON_PROPERTY_HUB_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHubId(@jakarta.annotation.Nonnull String hubId) {
    this.hubId = hubId;
  }

  public HubRegistrationResponse queueName(@jakarta.annotation.Nonnull String queueName) {
    
    this.queueName = queueName;
    return this;
  }

  /**
   * Name of the auto-delete queue the Server provisioned for this Hub. The Hub binds user routing keys to it and consumes it; the Hub never declares queues itself.
   * @return queueName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUEUE_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getQueueName() {
    return queueName;
  }


  @JsonProperty(value = JSON_PROPERTY_QUEUE_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQueueName(@jakarta.annotation.Nonnull String queueName) {
    this.queueName = queueName;
  }

  public HubRegistrationResponse exchange(@jakarta.annotation.Nonnull String exchange) {
    
    this.exchange = exchange;
    return this;
  }

  /**
   * Name of the topic exchange the Hub binds user routing keys against (messages.exchange).
   * @return exchange
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXCHANGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExchange() {
    return exchange;
  }


  @JsonProperty(value = JSON_PROPERTY_EXCHANGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExchange(@jakarta.annotation.Nonnull String exchange) {
    this.exchange = exchange;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubRegistrationResponse hubRegistrationResponse = (HubRegistrationResponse) o;
    return Objects.equals(this.hubId, hubRegistrationResponse.hubId) &&
        Objects.equals(this.queueName, hubRegistrationResponse.queueName) &&
        Objects.equals(this.exchange, hubRegistrationResponse.exchange);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hubId, queueName, exchange);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubRegistrationResponse {\n");
    sb.append("    hubId: ").append(toIndentedString(hubId)).append("\n");
    sb.append("    queueName: ").append(toIndentedString(queueName)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

