/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Sent by a Hub to the Server on boot to obtain its relay queue. Authentication is via the registration bearer token (a shared secret in Phase 1; a dashboard-issued per-Hub token later). The body itself carries no trust.
 */
@JsonPropertyOrder({
  HubRegistrationRequest.JSON_PROPERTY_INSTANCE_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T14:00:55.009181600+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class HubRegistrationRequest {
  public static final String JSON_PROPERTY_INSTANCE_ID = "instanceId";
  @jakarta.annotation.Nullable
  private String instanceId;

  public HubRegistrationRequest() {
  }

  public HubRegistrationRequest instanceId(@jakarta.annotation.Nullable String instanceId) {
    
    this.instanceId = instanceId;
    return this;
  }

  /**
   * Optional Hub-chosen instance label reported for diagnostics/dashboard display only. The Server does not derive identity or trust from it; the authoritative hubId is assigned by the Server.
   * @return instanceId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INSTANCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInstanceId() {
    return instanceId;
  }


  @JsonProperty(value = JSON_PROPERTY_INSTANCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstanceId(@jakarta.annotation.Nullable String instanceId) {
    this.instanceId = instanceId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubRegistrationRequest hubRegistrationRequest = (HubRegistrationRequest) o;
    return Objects.equals(this.instanceId, hubRegistrationRequest.instanceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instanceId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubRegistrationRequest {\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

