/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.fourletters.dto.EncryptedMessage;
import net.fourletters.dto.GroupKeySet;
import net.fourletters.dto.MessageReceipt;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * InboxResponse
 */
@JsonPropertyOrder({
  InboxResponse.JSON_PROPERTY_MESSAGES,
  InboxResponse.JSON_PROPERTY_RECEIPTS,
  InboxResponse.JSON_PROPERTY_GROUP_KEYS,
  InboxResponse.JSON_PROPERTY_SERVER_STARTED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-22T14:10:45.096494+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class InboxResponse {
  public static final String JSON_PROPERTY_MESSAGES = "messages";
  @jakarta.annotation.Nonnull
  private List<EncryptedMessage> messages = new ArrayList<>();

  public static final String JSON_PROPERTY_RECEIPTS = "receipts";
  @jakarta.annotation.Nullable
  private List<MessageReceipt> receipts = new ArrayList<>();

  public static final String JSON_PROPERTY_GROUP_KEYS = "groupKeys";
  @jakarta.annotation.Nullable
  private List<GroupKeySet> groupKeys = new ArrayList<>();

  public static final String JSON_PROPERTY_SERVER_STARTED_AT = "serverStartedAt";
  @jakarta.annotation.Nullable
  private Long serverStartedAt;

  public InboxResponse() {
  }

  public InboxResponse messages(@jakarta.annotation.Nonnull List<EncryptedMessage> messages) {
    
    this.messages = messages;
    return this;
  }

  public InboxResponse addMessagesItem(EncryptedMessage messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<>();
    }
    this.messages.add(messagesItem);
    return this;
  }

  /**
   * The recipient&#39;s undelivered messages, in arrival order.
   * @return messages
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<EncryptedMessage> getMessages() {
    return messages;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessages(@jakarta.annotation.Nonnull List<EncryptedMessage> messages) {
    this.messages = messages;
  }

  public InboxResponse receipts(@jakarta.annotation.Nullable List<MessageReceipt> receipts) {
    
    this.receipts = receipts;
    return this;
  }

  public InboxResponse addReceiptsItem(MessageReceipt receiptsItem) {
    if (this.receipts == null) {
      this.receipts = new ArrayList<>();
    }
    this.receipts.add(receiptsItem);
    return this;
  }

  /**
   * Pending delivery/read acknowledgements for messages this user sent, accumulated while the user was offline. Returned once and then cleared.
   * @return receipts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECEIPTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MessageReceipt> getReceipts() {
    return receipts;
  }


  @JsonProperty(value = JSON_PROPERTY_RECEIPTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReceipts(@jakarta.annotation.Nullable List<MessageReceipt> receipts) {
    this.receipts = receipts;
  }

  public InboxResponse groupKeys(@jakarta.annotation.Nullable List<GroupKeySet> groupKeys) {
    
    this.groupKeys = groupKeys;
    return this;
  }

  public InboxResponse addGroupKeysItem(GroupKeySet groupKeysItem) {
    if (this.groupKeys == null) {
      this.groupKeys = new ArrayList<>();
    }
    this.groupKeys.add(groupKeysItem);
    return this;
  }

  /**
   * Wrapped group keys the caller is missing for groups they belong to — e.g. they were offline during a rotation or just joined. Each entry is the current epoch&#39;s key wrapped to the caller&#39;s encryption key. Folded into the inbox pull so reconnect is a single round-trip. Returned once and then cleared.
   * @return groupKeys
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GROUP_KEYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GroupKeySet> getGroupKeys() {
    return groupKeys;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP_KEYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupKeys(@jakarta.annotation.Nullable List<GroupKeySet> groupKeys) {
    this.groupKeys = groupKeys;
  }

  public InboxResponse serverStartedAt(@jakarta.annotation.Nullable Long serverStartedAt) {
    
    this.serverStartedAt = serverStartedAt;
    return this;
  }

  /**
   * Epoch milliseconds at which this Server process started. A changed value across responses signals a restart, after which the client re-submits its unconfirmed outbox messages.
   * @return serverStartedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVER_STARTED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getServerStartedAt() {
    return serverStartedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVER_STARTED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServerStartedAt(@jakarta.annotation.Nullable Long serverStartedAt) {
    this.serverStartedAt = serverStartedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InboxResponse inboxResponse = (InboxResponse) o;
    return Objects.equals(this.messages, inboxResponse.messages) &&
        Objects.equals(this.receipts, inboxResponse.receipts) &&
        Objects.equals(this.groupKeys, inboxResponse.groupKeys) &&
        Objects.equals(this.serverStartedAt, inboxResponse.serverStartedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messages, receipts, groupKeys, serverStartedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InboxResponse {\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    receipts: ").append(toIndentedString(receipts)).append("\n");
    sb.append("    groupKeys: ").append(toIndentedString(groupKeys)).append("\n");
    sb.append("    serverStartedAt: ").append(toIndentedString(serverStartedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

