/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import net.fourletters.dto.PublicKeySet;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * KeysResponse
 */
@JsonPropertyOrder({
  KeysResponse.JSON_PROPERTY_USER_ID,
  KeysResponse.JSON_PROPERTY_KEYS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-10T09:32:42.450536800+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class KeysResponse {
  public static final String JSON_PROPERTY_USER_ID = "userId";
  @jakarta.annotation.Nonnull
  private UUID userId;

  public static final String JSON_PROPERTY_KEYS = "keys";
  @jakarta.annotation.Nonnull
  private PublicKeySet keys;

  public KeysResponse() {
  }

  public KeysResponse userId(@jakarta.annotation.Nonnull UUID userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * The user id these public keys belong to.
   * @return userId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getUserId() {
    return userId;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@jakarta.annotation.Nonnull UUID userId) {
    this.userId = userId;
  }

  public KeysResponse keys(@jakarta.annotation.Nonnull PublicKeySet keys) {
    
    this.keys = keys;
    return this;
  }

  /**
   * Get keys
   * @return keys
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PublicKeySet getKeys() {
    return keys;
  }


  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeys(@jakarta.annotation.Nonnull PublicKeySet keys) {
    this.keys = keys;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeysResponse keysResponse = (KeysResponse) o;
    return Objects.equals(this.userId, keysResponse.userId) &&
        Objects.equals(this.keys, keysResponse.keys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, keys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeysResponse {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

