/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.fourletters.dto.OneTimePreKey;
import net.fourletters.dto.SignedPreKey;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Uploads the caller&#39;s Signal pre-key bundle (identity, registration id, signed pre-key, and a pool of one-time pre-keys), replacing any previous bundle. Sent on first login of a new device.
 */
@JsonPropertyOrder({
  KeysUploadRequest.JSON_PROPERTY_REGISTRATION_ID,
  KeysUploadRequest.JSON_PROPERTY_IDENTITY_KEY,
  KeysUploadRequest.JSON_PROPERTY_SIGNED_PRE_KEY,
  KeysUploadRequest.JSON_PROPERTY_ONE_TIME_PRE_KEYS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-06T15:05:45.914087500+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class KeysUploadRequest {
  public static final String JSON_PROPERTY_REGISTRATION_ID = "registrationId";
  @jakarta.annotation.Nonnull
  private Integer registrationId;

  public static final String JSON_PROPERTY_IDENTITY_KEY = "identityKey";
  @jakarta.annotation.Nonnull
  private String identityKey;

  public static final String JSON_PROPERTY_SIGNED_PRE_KEY = "signedPreKey";
  @jakarta.annotation.Nonnull
  private SignedPreKey signedPreKey;

  public static final String JSON_PROPERTY_ONE_TIME_PRE_KEYS = "oneTimePreKeys";
  @jakarta.annotation.Nonnull
  private List<OneTimePreKey> oneTimePreKeys = new ArrayList<>();

  public KeysUploadRequest() {
  }

  public KeysUploadRequest registrationId(@jakarta.annotation.Nonnull Integer registrationId) {
    
    this.registrationId = registrationId;
    return this;
  }

  /**
   * The caller&#39;s Signal registration id.
   * @return registrationId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REGISTRATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getRegistrationId() {
    return registrationId;
  }


  @JsonProperty(value = JSON_PROPERTY_REGISTRATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRegistrationId(@jakarta.annotation.Nonnull Integer registrationId) {
    this.registrationId = registrationId;
  }

  public KeysUploadRequest identityKey(@jakarta.annotation.Nonnull String identityKey) {
    
    this.identityKey = identityKey;
    return this;
  }

  /**
   * The caller&#39;s long-lived Curve25519 identity public key (Base64).
   * @return identityKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IDENTITY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIdentityKey() {
    return identityKey;
  }


  @JsonProperty(value = JSON_PROPERTY_IDENTITY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentityKey(@jakarta.annotation.Nonnull String identityKey) {
    this.identityKey = identityKey;
  }

  public KeysUploadRequest signedPreKey(@jakarta.annotation.Nonnull SignedPreKey signedPreKey) {
    
    this.signedPreKey = signedPreKey;
    return this;
  }

  /**
   * Get signedPreKey
   * @return signedPreKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SIGNED_PRE_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SignedPreKey getSignedPreKey() {
    return signedPreKey;
  }


  @JsonProperty(value = JSON_PROPERTY_SIGNED_PRE_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignedPreKey(@jakarta.annotation.Nonnull SignedPreKey signedPreKey) {
    this.signedPreKey = signedPreKey;
  }

  public KeysUploadRequest oneTimePreKeys(@jakarta.annotation.Nonnull List<OneTimePreKey> oneTimePreKeys) {
    
    this.oneTimePreKeys = oneTimePreKeys;
    return this;
  }

  public KeysUploadRequest addOneTimePreKeysItem(OneTimePreKey oneTimePreKeysItem) {
    if (this.oneTimePreKeys == null) {
      this.oneTimePreKeys = new ArrayList<>();
    }
    this.oneTimePreKeys.add(oneTimePreKeysItem);
    return this;
  }

  /**
   * Initial pool of one-time pre-keys; the server hands one out per session and deletes it.
   * @return oneTimePreKeys
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ONE_TIME_PRE_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<OneTimePreKey> getOneTimePreKeys() {
    return oneTimePreKeys;
  }


  @JsonProperty(value = JSON_PROPERTY_ONE_TIME_PRE_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOneTimePreKeys(@jakarta.annotation.Nonnull List<OneTimePreKey> oneTimePreKeys) {
    this.oneTimePreKeys = oneTimePreKeys;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeysUploadRequest keysUploadRequest = (KeysUploadRequest) o;
    return Objects.equals(this.registrationId, keysUploadRequest.registrationId) &&
        Objects.equals(this.identityKey, keysUploadRequest.identityKey) &&
        Objects.equals(this.signedPreKey, keysUploadRequest.signedPreKey) &&
        Objects.equals(this.oneTimePreKeys, keysUploadRequest.oneTimePreKeys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(registrationId, identityKey, signedPreKey, oneTimePreKeys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeysUploadRequest {\n");
    sb.append("    registrationId: ").append(toIndentedString(registrationId)).append("\n");
    sb.append("    identityKey: ").append(toIndentedString(identityKey)).append("\n");
    sb.append("    signedPreKey: ").append(toIndentedString(signedPreKey)).append("\n");
    sb.append("    oneTimePreKeys: ").append(toIndentedString(oneTimePreKeys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

