/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * KeysUploadRequest
 */
@JsonPropertyOrder({
  KeysUploadRequest.JSON_PROPERTY_SIGNING_PUBLIC_KEY,
  KeysUploadRequest.JSON_PROPERTY_ENCRYPTION_PUBLIC_KEY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-22T14:10:45.096494+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class KeysUploadRequest {
  public static final String JSON_PROPERTY_SIGNING_PUBLIC_KEY = "signingPublicKey";
  @jakarta.annotation.Nonnull
  private String signingPublicKey;

  public static final String JSON_PROPERTY_ENCRYPTION_PUBLIC_KEY = "encryptionPublicKey";
  @jakarta.annotation.Nonnull
  private String encryptionPublicKey;

  public KeysUploadRequest() {
  }

  public KeysUploadRequest signingPublicKey(@jakarta.annotation.Nonnull String signingPublicKey) {
    
    this.signingPublicKey = signingPublicKey;
    return this;
  }

  /**
   * The caller&#39;s ECDSA P-256 public signing key (Base64 SPKI).
   * @return signingPublicKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SIGNING_PUBLIC_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSigningPublicKey() {
    return signingPublicKey;
  }


  @JsonProperty(value = JSON_PROPERTY_SIGNING_PUBLIC_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSigningPublicKey(@jakarta.annotation.Nonnull String signingPublicKey) {
    this.signingPublicKey = signingPublicKey;
  }

  public KeysUploadRequest encryptionPublicKey(@jakarta.annotation.Nonnull String encryptionPublicKey) {
    
    this.encryptionPublicKey = encryptionPublicKey;
    return this;
  }

  /**
   * The caller&#39;s ECDH P-256 public encryption key (Base64 SPKI).
   * @return encryptionPublicKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ENCRYPTION_PUBLIC_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEncryptionPublicKey() {
    return encryptionPublicKey;
  }


  @JsonProperty(value = JSON_PROPERTY_ENCRYPTION_PUBLIC_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEncryptionPublicKey(@jakarta.annotation.Nonnull String encryptionPublicKey) {
    this.encryptionPublicKey = encryptionPublicKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeysUploadRequest keysUploadRequest = (KeysUploadRequest) o;
    return Objects.equals(this.signingPublicKey, keysUploadRequest.signingPublicKey) &&
        Objects.equals(this.encryptionPublicKey, keysUploadRequest.encryptionPublicKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signingPublicKey, encryptionPublicKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeysUploadRequest {\n");
    sb.append("    signingPublicKey: ").append(toIndentedString(signingPublicKey)).append("\n");
    sb.append("    encryptionPublicKey: ").append(toIndentedString(encryptionPublicKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

