/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.fourletters.dto.AcceptedResponse;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MessageBatchResponse
 */
@JsonPropertyOrder({
  MessageBatchResponse.JSON_PROPERTY_RESULTS,
  MessageBatchResponse.JSON_PROPERTY_SERVER_STARTED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T18:22:19.048480100+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class MessageBatchResponse {
  public static final String JSON_PROPERTY_RESULTS = "results";
  @jakarta.annotation.Nonnull
  private List<AcceptedResponse> results = new ArrayList<>();

  public static final String JSON_PROPERTY_SERVER_STARTED_AT = "serverStartedAt";
  @jakarta.annotation.Nonnull
  private Long serverStartedAt;

  public MessageBatchResponse() {
  }

  public MessageBatchResponse results(@jakarta.annotation.Nonnull List<AcceptedResponse> results) {
    
    this.results = results;
    return this;
  }

  public MessageBatchResponse addResultsItem(AcceptedResponse resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

  /**
   * Per-message acceptance result, in request order.
   * @return results
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESULTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<AcceptedResponse> getResults() {
    return results;
  }


  @JsonProperty(value = JSON_PROPERTY_RESULTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResults(@jakarta.annotation.Nonnull List<AcceptedResponse> results) {
    this.results = results;
  }

  public MessageBatchResponse serverStartedAt(@jakarta.annotation.Nonnull Long serverStartedAt) {
    
    this.serverStartedAt = serverStartedAt;
    return this;
  }

  /**
   * Epoch milliseconds at which this Server process started (carried once for the whole batch).
   * @return serverStartedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SERVER_STARTED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getServerStartedAt() {
    return serverStartedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVER_STARTED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setServerStartedAt(@jakarta.annotation.Nonnull Long serverStartedAt) {
    this.serverStartedAt = serverStartedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageBatchResponse messageBatchResponse = (MessageBatchResponse) o;
    return Objects.equals(this.results, messageBatchResponse.results) &&
        Objects.equals(this.serverStartedAt, messageBatchResponse.serverStartedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(results, serverStartedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageBatchResponse {\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    serverStartedAt: ").append(toIndentedString(serverStartedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

