/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.fourletters.dto.EncryptedMessage;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Submits several messages in one call — used by the client to re-submit unconfirmed outbox messages after a detected Server restart. Idempotent per messageId.
 */
@JsonPropertyOrder({
  MessageBatchRequest.JSON_PROPERTY_MESSAGES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T19:09:22.768486900+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class MessageBatchRequest {
  public static final String JSON_PROPERTY_MESSAGES = "messages";
  @jakarta.annotation.Nonnull
  private List<EncryptedMessage> messages = new ArrayList<>();

  public MessageBatchRequest() {
  }

  public MessageBatchRequest messages(@jakarta.annotation.Nonnull List<EncryptedMessage> messages) {
    
    this.messages = messages;
    return this;
  }

  public MessageBatchRequest addMessagesItem(EncryptedMessage messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<>();
    }
    this.messages.add(messagesItem);
    return this;
  }

  /**
   * The messages to (re)submit, capped per request; the client chunks larger resyncs.
   * @return messages
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<EncryptedMessage> getMessages() {
    return messages;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessages(@jakarta.annotation.Nonnull List<EncryptedMessage> messages) {
    this.messages = messages;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageBatchRequest messageBatchRequest = (MessageBatchRequest) o;
    return Objects.equals(this.messages, messageBatchRequest.messages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageBatchRequest {\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

