/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import net.fourletters.dto.MessageAcknowledgement;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MessageDispatchedPayload
 */
@JsonPropertyOrder({
  MessageDispatchedPayload.JSON_PROPERTY_EVENT,
  MessageDispatchedPayload.JSON_PROPERTY_DATA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-11T13:24:57.506629+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class MessageDispatchedPayload {
  public static final String JSON_PROPERTY_EVENT = "event";
  @jakarta.annotation.Nonnull
  private String event;

  public static final String JSON_PROPERTY_DATA = "data";
  @jakarta.annotation.Nonnull
  private MessageAcknowledgement data;

  public MessageDispatchedPayload() {
  }

  public MessageDispatchedPayload event(@jakarta.annotation.Nonnull String event) {
    
    this.event = event;
    return this;
  }

  /**
   * Get event
   * @return event
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEvent() {
    return event;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEvent(@jakarta.annotation.Nonnull String event) {
    this.event = event;
  }

  public MessageDispatchedPayload data(@jakarta.annotation.Nonnull MessageAcknowledgement data) {
    
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MessageAcknowledgement getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(@jakarta.annotation.Nonnull MessageAcknowledgement data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageDispatchedPayload messageDispatchedPayload = (MessageDispatchedPayload) o;
    return Objects.equals(this.event, messageDispatchedPayload.event) &&
        Objects.equals(this.data, messageDispatchedPayload.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(event, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageDispatchedPayload {\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

