/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A delivery/read acknowledgement for a message the calling user sent, delivered to the sender via the inbox pull.
 */
@JsonPropertyOrder({
  MessageReceipt.JSON_PROPERTY_MESSAGE_ID,
  MessageReceipt.JSON_PROPERTY_RECIPIENT_ID,
  MessageReceipt.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T19:09:22.768486900+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class MessageReceipt {
  public static final String JSON_PROPERTY_MESSAGE_ID = "messageId";
  @jakarta.annotation.Nonnull
  private UUID messageId;

  public static final String JSON_PROPERTY_RECIPIENT_ID = "recipientId";
  @jakarta.annotation.Nonnull
  private UUID recipientId;

  /**
   * &#39;delivered&#39; &#x3D; received and decrypted; &#39;read&#39; &#x3D; opened by the user.
   */
  public enum TypeEnum {
    DELIVERED(String.valueOf("delivered")),
    
    READ(String.valueOf("read"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public MessageReceipt() {
  }

  public MessageReceipt messageId(@jakarta.annotation.Nonnull UUID messageId) {
    
    this.messageId = messageId;
    return this;
  }

  /**
   * ID of the original message being acknowledged.
   * @return messageId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getMessageId() {
    return messageId;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageId(@jakarta.annotation.Nonnull UUID messageId) {
    this.messageId = messageId;
  }

  public MessageReceipt recipientId(@jakarta.annotation.Nonnull UUID recipientId) {
    
    this.recipientId = recipientId;
    return this;
  }

  /**
   * ID of the user who delivered/read the message.
   * @return recipientId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECIPIENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getRecipientId() {
    return recipientId;
  }


  @JsonProperty(value = JSON_PROPERTY_RECIPIENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecipientId(@jakarta.annotation.Nonnull UUID recipientId) {
    this.recipientId = recipientId;
  }

  public MessageReceipt type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * &#39;delivered&#39; &#x3D; received and decrypted; &#39;read&#39; &#x3D; opened by the user.
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageReceipt messageReceipt = (MessageReceipt) o;
    return Objects.equals(this.messageId, messageReceipt.messageId) &&
        Objects.equals(this.recipientId, messageReceipt.recipientId) &&
        Objects.equals(this.type, messageReceipt.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageId, recipientId, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageReceipt {\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    recipientId: ").append(toIndentedString(recipientId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

