/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A Signal one-time pre-key, consumed once when a peer opens a session.
 */
@JsonPropertyOrder({
  OneTimePreKey.JSON_PROPERTY_KEY_ID,
  OneTimePreKey.JSON_PROPERTY_PUBLIC_KEY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-26T13:12:30.193024900+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class OneTimePreKey {
  public static final String JSON_PROPERTY_KEY_ID = "keyId";
  @jakarta.annotation.Nonnull
  private Integer keyId;

  public static final String JSON_PROPERTY_PUBLIC_KEY = "publicKey";
  @jakarta.annotation.Nonnull
  private String publicKey;

  public OneTimePreKey() {
  }

  public OneTimePreKey keyId(@jakarta.annotation.Nonnull Integer keyId) {
    
    this.keyId = keyId;
    return this;
  }

  /**
   * Client-assigned id of this one-time pre-key.
   * @return keyId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getKeyId() {
    return keyId;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeyId(@jakarta.annotation.Nonnull Integer keyId) {
    this.keyId = keyId;
  }

  public OneTimePreKey publicKey(@jakarta.annotation.Nonnull String publicKey) {
    
    this.publicKey = publicKey;
    return this;
  }

  /**
   * Curve25519 one-time pre-key public key (Base64).
   * @return publicKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PUBLIC_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPublicKey() {
    return publicKey;
  }


  @JsonProperty(value = JSON_PROPERTY_PUBLIC_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPublicKey(@jakarta.annotation.Nonnull String publicKey) {
    this.publicKey = publicKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OneTimePreKey oneTimePreKey = (OneTimePreKey) o;
    return Objects.equals(this.keyId, oneTimePreKey.keyId) &&
        Objects.equals(this.publicKey, oneTimePreKey.publicKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keyId, publicKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OneTimePreKey {\n");
    sb.append("    keyId: ").append(toIndentedString(keyId)).append("\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

