/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.fourletters.dto.OneTimePreKeyDto;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Replenishes the caller&#39;s pool of one-time pre-keys when it runs low.
 */
@JsonPropertyOrder({
  PreKeysUploadRequest.JSON_PROPERTY_ONE_TIME_PRE_KEYS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-24T17:06:31.125825+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class PreKeysUploadRequest {
  public static final String JSON_PROPERTY_ONE_TIME_PRE_KEYS = "oneTimePreKeys";
  @jakarta.annotation.Nonnull
  private List<OneTimePreKeyDto> oneTimePreKeys = new ArrayList<>();

  public PreKeysUploadRequest() {
  }

  public PreKeysUploadRequest oneTimePreKeys(@jakarta.annotation.Nonnull List<OneTimePreKeyDto> oneTimePreKeys) {
    
    this.oneTimePreKeys = oneTimePreKeys;
    return this;
  }

  public PreKeysUploadRequest addOneTimePreKeysItem(OneTimePreKeyDto oneTimePreKeysItem) {
    if (this.oneTimePreKeys == null) {
      this.oneTimePreKeys = new ArrayList<>();
    }
    this.oneTimePreKeys.add(oneTimePreKeysItem);
    return this;
  }

  /**
   * Additional one-time pre-keys to append to the caller&#39;s pool.
   * @return oneTimePreKeys
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ONE_TIME_PRE_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<OneTimePreKeyDto> getOneTimePreKeys() {
    return oneTimePreKeys;
  }


  @JsonProperty(value = JSON_PROPERTY_ONE_TIME_PRE_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOneTimePreKeys(@jakarta.annotation.Nonnull List<OneTimePreKeyDto> oneTimePreKeys) {
    this.oneTimePreKeys = oneTimePreKeys;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PreKeysUploadRequest preKeysUploadRequest = (PreKeysUploadRequest) o;
    return Objects.equals(this.oneTimePreKeys, preKeysUploadRequest.oneTimePreKeys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oneTimePreKeys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PreKeysUploadRequest {\n");
    sb.append("    oneTimePreKeys: ").append(toIndentedString(oneTimePreKeys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

