/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.fourletters.dto.KeysResponse;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PublicKeysBatchResponse
 */
@JsonPropertyOrder({
  PublicKeysBatchResponse.JSON_PROPERTY_RESULTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-19T09:41:14.179809800+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class PublicKeysBatchResponse {
  public static final String JSON_PROPERTY_RESULTS = "results";
  @jakarta.annotation.Nonnull
  private List<KeysResponse> results = new ArrayList<>();

  public PublicKeysBatchResponse() {
  }

  public PublicKeysBatchResponse results(@jakarta.annotation.Nonnull List<KeysResponse> results) {
    
    this.results = results;
    return this;
  }

  public PublicKeysBatchResponse addResultsItem(KeysResponse resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

  /**
   * Get results
   * @return results
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESULTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<KeysResponse> getResults() {
    return results;
  }


  @JsonProperty(value = JSON_PROPERTY_RESULTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResults(@jakarta.annotation.Nonnull List<KeysResponse> results) {
    this.results = results;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicKeysBatchResponse publicKeysBatchResponse = (PublicKeysBatchResponse) o;
    return Objects.equals(this.results, publicKeysBatchResponse.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(results);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicKeysBatchResponse {\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

