/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import net.fourletters.dto.OneTimePreKey;
import net.fourletters.dto.SignedPreKey;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A user&#39;s Signal pre-key bundle as served by the directory: identity, registration id, signed pre-key, and at most one one-time pre-key (absent when the pool is exhausted).
 */
@JsonPropertyOrder({
  PublicKeySet.JSON_PROPERTY_REGISTRATION_ID,
  PublicKeySet.JSON_PROPERTY_IDENTITY_KEY,
  PublicKeySet.JSON_PROPERTY_SIGNED_PRE_KEY,
  PublicKeySet.JSON_PROPERTY_ONE_TIME_PRE_KEY,
  PublicKeySet.JSON_PROPERTY_UPLOADED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-26T13:12:30.193024900+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class PublicKeySet {
  public static final String JSON_PROPERTY_REGISTRATION_ID = "registrationId";
  @jakarta.annotation.Nonnull
  private Integer registrationId;

  public static final String JSON_PROPERTY_IDENTITY_KEY = "identityKey";
  @jakarta.annotation.Nonnull
  private String identityKey;

  public static final String JSON_PROPERTY_SIGNED_PRE_KEY = "signedPreKey";
  @jakarta.annotation.Nonnull
  private SignedPreKey signedPreKey;

  public static final String JSON_PROPERTY_ONE_TIME_PRE_KEY = "oneTimePreKey";
  @jakarta.annotation.Nullable
  private OneTimePreKey oneTimePreKey;

  public static final String JSON_PROPERTY_UPLOADED_AT = "uploadedAt";
  @jakarta.annotation.Nonnull
  private Long uploadedAt;

  public PublicKeySet() {
  }

  public PublicKeySet registrationId(@jakarta.annotation.Nonnull Integer registrationId) {
    
    this.registrationId = registrationId;
    return this;
  }

  /**
   * The user&#39;s Signal registration id.
   * @return registrationId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REGISTRATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getRegistrationId() {
    return registrationId;
  }


  @JsonProperty(value = JSON_PROPERTY_REGISTRATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRegistrationId(@jakarta.annotation.Nonnull Integer registrationId) {
    this.registrationId = registrationId;
  }

  public PublicKeySet identityKey(@jakarta.annotation.Nonnull String identityKey) {
    
    this.identityKey = identityKey;
    return this;
  }

  /**
   * Long-lived Curve25519 identity public key (Base64).
   * @return identityKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IDENTITY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIdentityKey() {
    return identityKey;
  }


  @JsonProperty(value = JSON_PROPERTY_IDENTITY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentityKey(@jakarta.annotation.Nonnull String identityKey) {
    this.identityKey = identityKey;
  }

  public PublicKeySet signedPreKey(@jakarta.annotation.Nonnull SignedPreKey signedPreKey) {
    
    this.signedPreKey = signedPreKey;
    return this;
  }

  /**
   * Get signedPreKey
   * @return signedPreKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SIGNED_PRE_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SignedPreKey getSignedPreKey() {
    return signedPreKey;
  }


  @JsonProperty(value = JSON_PROPERTY_SIGNED_PRE_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignedPreKey(@jakarta.annotation.Nonnull SignedPreKey signedPreKey) {
    this.signedPreKey = signedPreKey;
  }

  public PublicKeySet oneTimePreKey(@jakarta.annotation.Nullable OneTimePreKey oneTimePreKey) {
    
    this.oneTimePreKey = oneTimePreKey;
    return this;
  }

  /**
   * Get oneTimePreKey
   * @return oneTimePreKey
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ONE_TIME_PRE_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OneTimePreKey getOneTimePreKey() {
    return oneTimePreKey;
  }


  @JsonProperty(value = JSON_PROPERTY_ONE_TIME_PRE_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOneTimePreKey(@jakarta.annotation.Nullable OneTimePreKey oneTimePreKey) {
    this.oneTimePreKey = oneTimePreKey;
  }

  public PublicKeySet uploadedAt(@jakarta.annotation.Nonnull Long uploadedAt) {
    
    this.uploadedAt = uploadedAt;
    return this;
  }

  /**
   * Epoch milliseconds when this bundle was uploaded to the directory.
   * @return uploadedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPLOADED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getUploadedAt() {
    return uploadedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPLOADED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUploadedAt(@jakarta.annotation.Nonnull Long uploadedAt) {
    this.uploadedAt = uploadedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicKeySet publicKeySet = (PublicKeySet) o;
    return Objects.equals(this.registrationId, publicKeySet.registrationId) &&
        Objects.equals(this.identityKey, publicKeySet.identityKey) &&
        Objects.equals(this.signedPreKey, publicKeySet.signedPreKey) &&
        Objects.equals(this.oneTimePreKey, publicKeySet.oneTimePreKey) &&
        Objects.equals(this.uploadedAt, publicKeySet.uploadedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(registrationId, identityKey, signedPreKey, oneTimePreKey, uploadedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicKeySet {\n");
    sb.append("    registrationId: ").append(toIndentedString(registrationId)).append("\n");
    sb.append("    identityKey: ").append(toIndentedString(identityKey)).append("\n");
    sb.append("    signedPreKey: ").append(toIndentedString(signedPreKey)).append("\n");
    sb.append("    oneTimePreKey: ").append(toIndentedString(oneTimePreKey)).append("\n");
    sb.append("    uploadedAt: ").append(toIndentedString(uploadedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

