/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The client keys of a Web Push (VAPID) subscription, used by the Server to encrypt push payloads end-to-end to the browser push service.
 */
@JsonPropertyOrder({
  PushSubscriptionKeys.JSON_PROPERTY_P256DH,
  PushSubscriptionKeys.JSON_PROPERTY_AUTH
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-16T11:55:01.971963700+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class PushSubscriptionKeys {
  public static final String JSON_PROPERTY_P256DH = "p256dh";
  @jakarta.annotation.Nonnull
  private String p256dh;

  public static final String JSON_PROPERTY_AUTH = "auth";
  @jakarta.annotation.Nonnull
  private String auth;

  public PushSubscriptionKeys() {
  }

  public PushSubscriptionKeys p256dh(@jakarta.annotation.Nonnull String p256dh) {
    
    this.p256dh = p256dh;
    return this;
  }

  /**
   * The subscription&#39;s P-256 ECDH public key (Base64url), as produced by the browser PushManager.
   * @return p256dh
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_P256DH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getP256dh() {
    return p256dh;
  }


  @JsonProperty(value = JSON_PROPERTY_P256DH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setP256dh(@jakarta.annotation.Nonnull String p256dh) {
    this.p256dh = p256dh;
  }

  public PushSubscriptionKeys auth(@jakarta.annotation.Nonnull String auth) {
    
    this.auth = auth;
    return this;
  }

  /**
   * The subscription&#39;s auth secret (Base64url), as produced by the browser PushManager.
   * @return auth
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAuth() {
    return auth;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuth(@jakarta.annotation.Nonnull String auth) {
    this.auth = auth;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PushSubscriptionKeys pushSubscriptionKeys = (PushSubscriptionKeys) o;
    return Objects.equals(this.p256dh, pushSubscriptionKeys.p256dh) &&
        Objects.equals(this.auth, pushSubscriptionKeys.auth);
  }

  @Override
  public int hashCode() {
    return Objects.hash(p256dh, auth);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PushSubscriptionKeys {\n");
    sb.append("    p256dh: ").append(toIndentedString(p256dh)).append("\n");
    sb.append("    auth: ").append(toIndentedString(auth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

