/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import net.fourletters.dto.PushSubscriptionKeys;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A browser Web Push (VAPID) subscription registered by an authenticated client so the Server can wake an offline recipient.
 */
@JsonPropertyOrder({
  PushSubscription.JSON_PROPERTY_ENDPOINT,
  PushSubscription.JSON_PROPERTY_EXPIRATION_TIME,
  PushSubscription.JSON_PROPERTY_KEYS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class PushSubscription {
  public static final String JSON_PROPERTY_ENDPOINT = "endpoint";
  @jakarta.annotation.Nonnull
  private String endpoint;

  public static final String JSON_PROPERTY_EXPIRATION_TIME = "expirationTime";
  @jakarta.annotation.Nullable
  private Long expirationTime;

  public static final String JSON_PROPERTY_KEYS = "keys";
  @jakarta.annotation.Nonnull
  private PushSubscriptionKeys keys;

  public PushSubscription() {
  }

  public PushSubscription endpoint(@jakarta.annotation.Nonnull String endpoint) {
    
    this.endpoint = endpoint;
    return this;
  }

  /**
   * The push service endpoint URL the Server delivers encrypted pushes to.
   * @return endpoint
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEndpoint() {
    return endpoint;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEndpoint(@jakarta.annotation.Nonnull String endpoint) {
    this.endpoint = endpoint;
  }

  public PushSubscription expirationTime(@jakarta.annotation.Nullable Long expirationTime) {
    
    this.expirationTime = expirationTime;
    return this;
  }

  /**
   * Optional epoch milliseconds at which the subscription expires, if the browser provided one.
   * @return expirationTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExpirationTime() {
    return expirationTime;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpirationTime(@jakarta.annotation.Nullable Long expirationTime) {
    this.expirationTime = expirationTime;
  }

  public PushSubscription keys(@jakarta.annotation.Nonnull PushSubscriptionKeys keys) {
    
    this.keys = keys;
    return this;
  }

  /**
   * Get keys
   * @return keys
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PushSubscriptionKeys getKeys() {
    return keys;
  }


  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeys(@jakarta.annotation.Nonnull PushSubscriptionKeys keys) {
    this.keys = keys;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PushSubscription pushSubscription = (PushSubscription) o;
    return Objects.equals(this.endpoint, pushSubscription.endpoint) &&
        Objects.equals(this.expirationTime, pushSubscription.expirationTime) &&
        Objects.equals(this.keys, pushSubscription.keys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpoint, expirationTime, keys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PushSubscription {\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    expirationTime: ").append(toIndentedString(expirationTime)).append("\n");
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

