/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.fourletters.dto.DeliveryReceipt;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Submits several signed receipts in one call.
 */
@JsonPropertyOrder({
  ReceiptBatchRequest.JSON_PROPERTY_RECEIPTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-16T11:55:01.971963700+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class ReceiptBatchRequest {
  public static final String JSON_PROPERTY_RECEIPTS = "receipts";
  @jakarta.annotation.Nonnull
  private List<DeliveryReceipt> receipts = new ArrayList<>();

  public ReceiptBatchRequest() {
  }

  public ReceiptBatchRequest receipts(@jakarta.annotation.Nonnull List<DeliveryReceipt> receipts) {
    
    this.receipts = receipts;
    return this;
  }

  public ReceiptBatchRequest addReceiptsItem(DeliveryReceipt receiptsItem) {
    if (this.receipts == null) {
      this.receipts = new ArrayList<>();
    }
    this.receipts.add(receiptsItem);
    return this;
  }

  /**
   * The signed receipts to record, capped per request.
   * @return receipts
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECEIPTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<DeliveryReceipt> getReceipts() {
    return receipts;
  }


  @JsonProperty(value = JSON_PROPERTY_RECEIPTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReceipts(@jakarta.annotation.Nonnull List<DeliveryReceipt> receipts) {
    this.receipts = receipts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReceiptBatchRequest receiptBatchRequest = (ReceiptBatchRequest) o;
    return Objects.equals(this.receipts, receiptBatchRequest.receipts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(receipts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReceiptBatchRequest {\n");
    sb.append("    receipts: ").append(toIndentedString(receipts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

