/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import net.fourletters.dto.ReceiptType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ReceiptData
 */
@JsonPropertyOrder({
  ReceiptData.JSON_PROPERTY_MESSAGE_ID,
  ReceiptData.JSON_PROPERTY_RECIPIENT_ID,
  ReceiptData.JSON_PROPERTY_TYPE,
  ReceiptData.JSON_PROPERTY_SIGNATURE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-10T09:32:42.450536800+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class ReceiptData {
  public static final String JSON_PROPERTY_MESSAGE_ID = "messageId";
  @jakarta.annotation.Nonnull
  private UUID messageId;

  public static final String JSON_PROPERTY_RECIPIENT_ID = "recipientId";
  @jakarta.annotation.Nonnull
  private UUID recipientId;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private ReceiptType type;

  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  @jakarta.annotation.Nonnull
  private String signature;

  public ReceiptData() {
  }

  public ReceiptData messageId(@jakarta.annotation.Nonnull UUID messageId) {
    
    this.messageId = messageId;
    return this;
  }

  /**
   * ID of the original message this receipt refers to.
   * @return messageId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getMessageId() {
    return messageId;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageId(@jakarta.annotation.Nonnull UUID messageId) {
    this.messageId = messageId;
  }

  public ReceiptData recipientId(@jakarta.annotation.Nonnull UUID recipientId) {
    
    this.recipientId = recipientId;
    return this;
  }

  /**
   * ID of the user who delivered/read the message (the original recipient).
   * @return recipientId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECIPIENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getRecipientId() {
    return recipientId;
  }


  @JsonProperty(value = JSON_PROPERTY_RECIPIENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecipientId(@jakarta.annotation.Nonnull UUID recipientId) {
    this.recipientId = recipientId;
  }

  public ReceiptData type(@jakarta.annotation.Nonnull ReceiptType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ReceiptType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull ReceiptType type) {
    this.type = type;
  }

  public ReceiptData signature(@jakarta.annotation.Nonnull String signature) {
    
    this.signature = signature;
    return this;
  }

  /**
   * Signature over (messageId, type, originalSenderId) by the recipient&#39;s identity key (Base64), relayed unaltered from the submitted DeliveryReceipt.
   * @return signature
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SIGNATURE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignature() {
    return signature;
  }


  @JsonProperty(value = JSON_PROPERTY_SIGNATURE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignature(@jakarta.annotation.Nonnull String signature) {
    this.signature = signature;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReceiptData receiptData = (ReceiptData) o;
    return Objects.equals(this.messageId, receiptData.messageId) &&
        Objects.equals(this.recipientId, receiptData.recipientId) &&
        Objects.equals(this.type, receiptData.type) &&
        Objects.equals(this.signature, receiptData.signature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageId, recipientId, type, signature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReceiptData {\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    recipientId: ").append(toIndentedString(recipientId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

