/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Body of a 401 from /auth/refresh. &#39;revoked&#39; means a newer login took over the single active device, on which the client wipes its local E2E identity keys; the other reasons just require re-authentication.
 */
@JsonPropertyOrder({
  RefreshError.JSON_PROPERTY_REASON
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-19T09:41:14.179809800+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class RefreshError {
  /**
   * &#39;revoked&#39; &#x3D; invalidated by a newer login (single-active-device takeover); &#39;expired&#39; &#x3D; refresh token past expiry; &#39;invalid&#39; &#x3D; malformed/missing or session mismatch.
   */
  public enum ReasonEnum {
    REVOKED(String.valueOf("revoked")),
    
    EXPIRED(String.valueOf("expired")),
    
    INVALID(String.valueOf("invalid"));

    private String value;

    ReasonEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ReasonEnum fromValue(String value) {
      for (ReasonEnum b : ReasonEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_REASON = "reason";
  @jakarta.annotation.Nonnull
  private ReasonEnum reason;

  public RefreshError() {
  }

  public RefreshError reason(@jakarta.annotation.Nonnull ReasonEnum reason) {
    
    this.reason = reason;
    return this;
  }

  /**
   * &#39;revoked&#39; &#x3D; invalidated by a newer login (single-active-device takeover); &#39;expired&#39; &#x3D; refresh token past expiry; &#39;invalid&#39; &#x3D; malformed/missing or session mismatch.
   * @return reason
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REASON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ReasonEnum getReason() {
    return reason;
  }


  @JsonProperty(value = JSON_PROPERTY_REASON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReason(@jakarta.annotation.Nonnull ReasonEnum reason) {
    this.reason = reason;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefreshError refreshError = (RefreshError) o;
    return Objects.equals(this.reason, refreshError.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefreshError {\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

