/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A Signal signed pre-key: a medium-lived Curve25519 public key signed by the identity key.
 */
@JsonPropertyOrder({
  SignedPreKey.JSON_PROPERTY_KEY_ID,
  SignedPreKey.JSON_PROPERTY_PUBLIC_KEY,
  SignedPreKey.JSON_PROPERTY_SIGNATURE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-10T09:32:42.450536800+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class SignedPreKey {
  public static final String JSON_PROPERTY_KEY_ID = "keyId";
  @jakarta.annotation.Nonnull
  private Integer keyId;

  public static final String JSON_PROPERTY_PUBLIC_KEY = "publicKey";
  @jakarta.annotation.Nonnull
  private String publicKey;

  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  @jakarta.annotation.Nonnull
  private String signature;

  public SignedPreKey() {
  }

  public SignedPreKey keyId(@jakarta.annotation.Nonnull Integer keyId) {
    
    this.keyId = keyId;
    return this;
  }

  /**
   * Client-assigned id of this signed pre-key.
   * @return keyId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getKeyId() {
    return keyId;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeyId(@jakarta.annotation.Nonnull Integer keyId) {
    this.keyId = keyId;
  }

  public SignedPreKey publicKey(@jakarta.annotation.Nonnull String publicKey) {
    
    this.publicKey = publicKey;
    return this;
  }

  /**
   * Curve25519 signed pre-key public key (Base64).
   * @return publicKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PUBLIC_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPublicKey() {
    return publicKey;
  }


  @JsonProperty(value = JSON_PROPERTY_PUBLIC_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPublicKey(@jakarta.annotation.Nonnull String publicKey) {
    this.publicKey = publicKey;
  }

  public SignedPreKey signature(@jakarta.annotation.Nonnull String signature) {
    
    this.signature = signature;
    return this;
  }

  /**
   * Identity-key signature over the signed pre-key public key (Base64).
   * @return signature
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SIGNATURE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignature() {
    return signature;
  }


  @JsonProperty(value = JSON_PROPERTY_SIGNATURE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignature(@jakarta.annotation.Nonnull String signature) {
    this.signature = signature;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignedPreKey signedPreKey = (SignedPreKey) o;
    return Objects.equals(this.keyId, signedPreKey.keyId) &&
        Objects.equals(this.publicKey, signedPreKey.publicKey) &&
        Objects.equals(this.signature, signedPreKey.signature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keyId, publicKey, signature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignedPreKey {\n");
    sb.append("    keyId: ").append(toIndentedString(keyId)).append("\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

