/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.fourletters.dto.TelemetryLogRecord;
import net.fourletters.dto.TelemetryResource;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A batch of client OpenTelemetry LogRecords submitted for server-side persistence as JSON lines.
 */
@JsonPropertyOrder({
  TelemetryLogBatch.JSON_PROPERTY_RESOURCE,
  TelemetryLogBatch.JSON_PROPERTY_LOG_RECORDS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class TelemetryLogBatch {
  public static final String JSON_PROPERTY_RESOURCE = "resource";
  @jakarta.annotation.Nullable
  private TelemetryResource resource;

  public static final String JSON_PROPERTY_LOG_RECORDS = "logRecords";
  @jakarta.annotation.Nonnull
  private List<TelemetryLogRecord> logRecords = new ArrayList<>();

  public TelemetryLogBatch() {
  }

  public TelemetryLogBatch resource(@jakarta.annotation.Nullable TelemetryResource resource) {
    
    this.resource = resource;
    return this;
  }

  /**
   * Get resource
   * @return resource
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TelemetryResource getResource() {
    return resource;
  }


  @JsonProperty(value = JSON_PROPERTY_RESOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResource(@jakarta.annotation.Nullable TelemetryResource resource) {
    this.resource = resource;
  }

  public TelemetryLogBatch logRecords(@jakarta.annotation.Nonnull List<TelemetryLogRecord> logRecords) {
    
    this.logRecords = logRecords;
    return this;
  }

  public TelemetryLogBatch addLogRecordsItem(TelemetryLogRecord logRecordsItem) {
    if (this.logRecords == null) {
      this.logRecords = new ArrayList<>();
    }
    this.logRecords.add(logRecordsItem);
    return this;
  }

  /**
   * The captured LogRecords, capped per request.
   * @return logRecords
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LOG_RECORDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<TelemetryLogRecord> getLogRecords() {
    return logRecords;
  }


  @JsonProperty(value = JSON_PROPERTY_LOG_RECORDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLogRecords(@jakarta.annotation.Nonnull List<TelemetryLogRecord> logRecords) {
    this.logRecords = logRecords;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TelemetryLogBatch telemetryLogBatch = (TelemetryLogBatch) o;
    return Objects.equals(this.resource, telemetryLogBatch.resource) &&
        Objects.equals(this.logRecords, telemetryLogBatch.logRecords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resource, logRecords);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TelemetryLogBatch {\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    logRecords: ").append(toIndentedString(logRecords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

