/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A single OpenTelemetry LogRecord captured on the client. Carries only redacted diagnostics — never end-to-end message content, keys, or tokens.
 */
@JsonPropertyOrder({
  TelemetryLogRecord.JSON_PROPERTY_TIME_UNIX_NANO,
  TelemetryLogRecord.JSON_PROPERTY_SEVERITY_TEXT,
  TelemetryLogRecord.JSON_PROPERTY_SEVERITY_NUMBER,
  TelemetryLogRecord.JSON_PROPERTY_BODY,
  TelemetryLogRecord.JSON_PROPERTY_ATTRIBUTES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class TelemetryLogRecord {
  public static final String JSON_PROPERTY_TIME_UNIX_NANO = "timeUnixNano";
  @jakarta.annotation.Nonnull
  private String timeUnixNano;

  /**
   * OTel severity text. Only warnings and errors are captured.
   */
  public enum SeverityTextEnum {
    WARN(String.valueOf("WARN")),
    
    ERROR(String.valueOf("ERROR"));

    private String value;

    SeverityTextEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SeverityTextEnum fromValue(String value) {
      for (SeverityTextEnum b : SeverityTextEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SEVERITY_TEXT = "severityText";
  @jakarta.annotation.Nonnull
  private SeverityTextEnum severityText;

  public static final String JSON_PROPERTY_SEVERITY_NUMBER = "severityNumber";
  @jakarta.annotation.Nullable
  private Integer severityNumber;

  public static final String JSON_PROPERTY_BODY = "body";
  @jakarta.annotation.Nonnull
  private String body;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  @jakarta.annotation.Nullable
  private Map<String, Object> attributes = new HashMap<>();

  public TelemetryLogRecord() {
  }

  public TelemetryLogRecord timeUnixNano(@jakarta.annotation.Nonnull String timeUnixNano) {
    
    this.timeUnixNano = timeUnixNano;
    return this;
  }

  /**
   * Event time as OTel Unix nanoseconds — an int64 encoded as a decimal string (OTLP/JSON convention), avoiding client-side number precision loss.
   * @return timeUnixNano
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIME_UNIX_NANO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTimeUnixNano() {
    return timeUnixNano;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME_UNIX_NANO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimeUnixNano(@jakarta.annotation.Nonnull String timeUnixNano) {
    this.timeUnixNano = timeUnixNano;
  }

  public TelemetryLogRecord severityText(@jakarta.annotation.Nonnull SeverityTextEnum severityText) {
    
    this.severityText = severityText;
    return this;
  }

  /**
   * OTel severity text. Only warnings and errors are captured.
   * @return severityText
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEVERITY_TEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SeverityTextEnum getSeverityText() {
    return severityText;
  }


  @JsonProperty(value = JSON_PROPERTY_SEVERITY_TEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeverityText(@jakarta.annotation.Nonnull SeverityTextEnum severityText) {
    this.severityText = severityText;
  }

  public TelemetryLogRecord severityNumber(@jakarta.annotation.Nullable Integer severityNumber) {
    
    this.severityNumber = severityNumber;
    return this;
  }

  /**
   * OTel SeverityNumber (WARN&#x3D;13, ERROR&#x3D;17).
   * @return severityNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEVERITY_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeverityNumber() {
    return severityNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_SEVERITY_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeverityNumber(@jakarta.annotation.Nullable Integer severityNumber) {
    this.severityNumber = severityNumber;
  }

  public TelemetryLogRecord body(@jakarta.annotation.Nonnull String body) {
    
    this.body = body;
    return this;
  }

  /**
   * The log message body (redacted).
   * @return body
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BODY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBody() {
    return body;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBody(@jakarta.annotation.Nonnull String body) {
    this.body = body;
  }

  public TelemetryLogRecord attributes(@jakarta.annotation.Nullable Map<String, Object> attributes) {
    
    this.attributes = attributes;
    return this;
  }

  public TelemetryLogRecord putAttributesItem(String key, Object attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

  /**
   * Redacted OTel attributes (e.g. route, error.name, error.stack, http.status). Must never contain plaintext message content, ciphertext, keys, or auth tokens.
   * @return attributes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ATTRIBUTES, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getAttributes() {
    return attributes;
  }


  @JsonProperty(value = JSON_PROPERTY_ATTRIBUTES, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttributes(@jakarta.annotation.Nullable Map<String, Object> attributes) {
    this.attributes = attributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TelemetryLogRecord telemetryLogRecord = (TelemetryLogRecord) o;
    return Objects.equals(this.timeUnixNano, telemetryLogRecord.timeUnixNano) &&
        Objects.equals(this.severityText, telemetryLogRecord.severityText) &&
        Objects.equals(this.severityNumber, telemetryLogRecord.severityNumber) &&
        Objects.equals(this.body, telemetryLogRecord.body) &&
        Objects.equals(this.attributes, telemetryLogRecord.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeUnixNano, severityText, severityNumber, body, attributes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TelemetryLogRecord {\n");
    sb.append("    timeUnixNano: ").append(toIndentedString(timeUnixNano)).append("\n");
    sb.append("    severityText: ").append(toIndentedString(severityText)).append("\n");
    sb.append("    severityNumber: ").append(toIndentedString(severityNumber)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

