/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OpenTelemetry resource attributes describing the client that produced the log records. Attached once per batch and merged into every persisted LogRecord.
 */
@JsonPropertyOrder({
  TelemetryResource.JSON_PROPERTY_SERVICE_NAME,
  TelemetryResource.JSON_PROPERTY_SERVICE_VERSION,
  TelemetryResource.JSON_PROPERTY_SESSION_ID,
  TelemetryResource.JSON_PROPERTY_USER_AGENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class TelemetryResource {
  public static final String JSON_PROPERTY_SERVICE_NAME = "serviceName";
  @jakarta.annotation.Nullable
  private String serviceName;

  public static final String JSON_PROPERTY_SERVICE_VERSION = "serviceVersion";
  @jakarta.annotation.Nullable
  private String serviceVersion;

  public static final String JSON_PROPERTY_SESSION_ID = "sessionId";
  @jakarta.annotation.Nullable
  private String sessionId;

  public static final String JSON_PROPERTY_USER_AGENT = "userAgent";
  @jakarta.annotation.Nullable
  private String userAgent;

  public TelemetryResource() {
  }

  public TelemetryResource serviceName(@jakarta.annotation.Nullable String serviceName) {
    
    this.serviceName = serviceName;
    return this;
  }

  /**
   * OTel service.name of the emitting client (e.g. &#39;fourletters-gui&#39;).
   * @return serviceName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceName() {
    return serviceName;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceName(@jakarta.annotation.Nullable String serviceName) {
    this.serviceName = serviceName;
  }

  public TelemetryResource serviceVersion(@jakarta.annotation.Nullable String serviceVersion) {
    
    this.serviceVersion = serviceVersion;
    return this;
  }

  /**
   * OTel service.version — the client app/build version.
   * @return serviceVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceVersion() {
    return serviceVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceVersion(@jakarta.annotation.Nullable String serviceVersion) {
    this.serviceVersion = serviceVersion;
  }

  public TelemetryResource sessionId(@jakarta.annotation.Nullable String sessionId) {
    
    this.sessionId = sessionId;
    return this;
  }

  /**
   * Client-generated session id correlating all records from one app run. Never a user identifier.
   * @return sessionId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSessionId() {
    return sessionId;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionId(@jakarta.annotation.Nullable String sessionId) {
    this.sessionId = sessionId;
  }

  public TelemetryResource userAgent(@jakarta.annotation.Nullable String userAgent) {
    
    this.userAgent = userAgent;
    return this;
  }

  /**
   * Browser user agent string of the client.
   * @return userAgent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserAgent() {
    return userAgent;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserAgent(@jakarta.annotation.Nullable String userAgent) {
    this.userAgent = userAgent;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TelemetryResource telemetryResource = (TelemetryResource) o;
    return Objects.equals(this.serviceName, telemetryResource.serviceName) &&
        Objects.equals(this.serviceVersion, telemetryResource.serviceVersion) &&
        Objects.equals(this.sessionId, telemetryResource.sessionId) &&
        Objects.equals(this.userAgent, telemetryResource.userAgent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceName, serviceVersion, sessionId, userAgent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TelemetryResource {\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    serviceVersion: ").append(toIndentedString(serviceVersion)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

