/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Client -&gt; Hub: announce typing to exactly one destination: recipientId for a direct chat or groupId for a group. The Hub validates destination exclusivity and derives the sender from authentication.
 */
@JsonPropertyOrder({
  TypingCommand.JSON_PROPERTY_TYPE,
  TypingCommand.JSON_PROPERTY_RECIPIENT_ID,
  TypingCommand.JSON_PROPERTY_GROUP_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class TypingCommand {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    TYPING(String.valueOf("typing"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_RECIPIENT_ID = "recipientId";
  @jakarta.annotation.Nullable
  private UUID recipientId;

  public static final String JSON_PROPERTY_GROUP_ID = "groupId";
  @jakarta.annotation.Nullable
  private UUID groupId;

  public TypingCommand() {
  }

  public TypingCommand type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public TypingCommand recipientId(@jakarta.annotation.Nullable UUID recipientId) {
    
    this.recipientId = recipientId;
    return this;
  }

  /**
   * Direct recipient; routed to typing.user.&lt;recipientId&gt;.
   * @return recipientId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECIPIENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getRecipientId() {
    return recipientId;
  }


  @JsonProperty(value = JSON_PROPERTY_RECIPIENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecipientId(@jakarta.annotation.Nullable UUID recipientId) {
    this.recipientId = recipientId;
  }

  public TypingCommand groupId(@jakarta.annotation.Nullable UUID groupId) {
    
    this.groupId = groupId;
    return this;
  }

  /**
   * Group destination; routed to typing.group.&lt;groupId&gt;.
   * @return groupId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GROUP_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getGroupId() {
    return groupId;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupId(@jakarta.annotation.Nullable UUID groupId) {
    this.groupId = groupId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TypingCommand typingCommand = (TypingCommand) o;
    return Objects.equals(this.type, typingCommand.type) &&
        Objects.equals(this.recipientId, typingCommand.recipientId) &&
        Objects.equals(this.groupId, typingCommand.groupId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, recipientId, groupId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TypingCommand {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    recipientId: ").append(toIndentedString(recipientId)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

