/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import net.fourletters.dto.WrappedGroupKey;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Owner-only roster change. Adding and/or removing members always rotates: the body carries the new epoch&#39;s full wrapped-key set for the resulting roster. Compare-and-swap on epoch.
 */
@JsonPropertyOrder({
  UpdateMembersRequest.JSON_PROPERTY_ADD,
  UpdateMembersRequest.JSON_PROPERTY_REMOVE,
  UpdateMembersRequest.JSON_PROPERTY_EPOCH,
  UpdateMembersRequest.JSON_PROPERTY_KEYS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-22T14:10:45.096494+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class UpdateMembersRequest {
  public static final String JSON_PROPERTY_ADD = "add";
  @jakarta.annotation.Nullable
  private List<UUID> add = new ArrayList<>();

  public static final String JSON_PROPERTY_REMOVE = "remove";
  @jakarta.annotation.Nullable
  private List<UUID> remove = new ArrayList<>();

  public static final String JSON_PROPERTY_EPOCH = "epoch";
  @jakarta.annotation.Nonnull
  private Long epoch;

  public static final String JSON_PROPERTY_KEYS = "keys";
  @jakarta.annotation.Nonnull
  private List<WrappedGroupKey> keys = new ArrayList<>();

  public UpdateMembersRequest() {
  }

  public UpdateMembersRequest add(@jakarta.annotation.Nullable List<UUID> add) {
    
    this.add = add;
    return this;
  }

  public UpdateMembersRequest addAddItem(UUID addItem) {
    if (this.add == null) {
      this.add = new ArrayList<>();
    }
    this.add.add(addItem);
    return this;
  }

  /**
   * User ids to add to the roster.
   * @return add
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UUID> getAdd() {
    return add;
  }


  @JsonProperty(value = JSON_PROPERTY_ADD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdd(@jakarta.annotation.Nullable List<UUID> add) {
    this.add = add;
  }

  public UpdateMembersRequest remove(@jakarta.annotation.Nullable List<UUID> remove) {
    
    this.remove = remove;
    return this;
  }

  public UpdateMembersRequest addRemoveItem(UUID removeItem) {
    if (this.remove == null) {
      this.remove = new ArrayList<>();
    }
    this.remove.add(removeItem);
    return this;
  }

  /**
   * User ids to remove from the roster.
   * @return remove
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REMOVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UUID> getRemove() {
    return remove;
  }


  @JsonProperty(value = JSON_PROPERTY_REMOVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRemove(@jakarta.annotation.Nullable List<UUID> remove) {
    this.remove = remove;
  }

  public UpdateMembersRequest epoch(@jakarta.annotation.Nonnull Long epoch) {
    
    this.epoch = epoch;
    return this;
  }

  /**
   * The new epoch (must equal current epoch + 1). Rejected with 409 on mismatch.
   * @return epoch
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EPOCH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getEpoch() {
    return epoch;
  }


  @JsonProperty(value = JSON_PROPERTY_EPOCH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEpoch(@jakarta.annotation.Nonnull Long epoch) {
    this.epoch = epoch;
  }

  public UpdateMembersRequest keys(@jakarta.annotation.Nonnull List<WrappedGroupKey> keys) {
    
    this.keys = keys;
    return this;
  }

  public UpdateMembersRequest addKeysItem(WrappedGroupKey keysItem) {
    if (this.keys == null) {
      this.keys = new ArrayList<>();
    }
    this.keys.add(keysItem);
    return this;
  }

  /**
   * The new epoch key wrapped to exactly the resulting roster (after add/remove).
   * @return keys
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<WrappedGroupKey> getKeys() {
    return keys;
  }


  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeys(@jakarta.annotation.Nonnull List<WrappedGroupKey> keys) {
    this.keys = keys;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateMembersRequest updateMembersRequest = (UpdateMembersRequest) o;
    return Objects.equals(this.add, updateMembersRequest.add) &&
        Objects.equals(this.remove, updateMembersRequest.remove) &&
        Objects.equals(this.epoch, updateMembersRequest.epoch) &&
        Objects.equals(this.keys, updateMembersRequest.keys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(add, remove, epoch, keys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateMembersRequest {\n");
    sb.append("    add: ").append(toIndentedString(add)).append("\n");
    sb.append("    remove: ").append(toIndentedString(remove)).append("\n");
    sb.append("    epoch: ").append(toIndentedString(epoch)).append("\n");
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

