/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Owner-only partial update of a group&#39;s metadata. Only the provided fields are changed.
 */
@JsonPropertyOrder({
  UpdateGroupRequest.JSON_PROPERTY_NAME,
  UpdateGroupRequest.JSON_PROPERTY_AVATAR_URL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class UpdateGroupRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_AVATAR_URL = "avatarUrl";
  @jakarta.annotation.Nullable
  private String avatarUrl;

  public UpdateGroupRequest() {
  }

  public UpdateGroupRequest name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * New group name (plaintext). Omit to leave unchanged.
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public UpdateGroupRequest avatarUrl(@jakarta.annotation.Nullable String avatarUrl) {
    
    this.avatarUrl = avatarUrl;
    return this;
  }

  /**
   * Base64 data URL to set the avatar, an empty string to clear it, or omit to leave it unchanged.
   * @return avatarUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVATAR_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAvatarUrl() {
    return avatarUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_AVATAR_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvatarUrl(@jakarta.annotation.Nullable String avatarUrl) {
    this.avatarUrl = avatarUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateGroupRequest updateGroupRequest = (UpdateGroupRequest) o;
    return Objects.equals(this.name, updateGroupRequest.name) &&
        Objects.equals(this.avatarUrl, updateGroupRequest.avatarUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, avatarUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateGroupRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

