/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Owner-only roster change.
 */
@JsonPropertyOrder({
  UpdateMembersRequest.JSON_PROPERTY_ADD,
  UpdateMembersRequest.JSON_PROPERTY_REMOVE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-24T17:06:31.125825+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class UpdateMembersRequest {
  public static final String JSON_PROPERTY_ADD = "add";
  @jakarta.annotation.Nullable
  private List<UUID> add = new ArrayList<>();

  public static final String JSON_PROPERTY_REMOVE = "remove";
  @jakarta.annotation.Nullable
  private List<UUID> remove = new ArrayList<>();

  public UpdateMembersRequest() {
  }

  public UpdateMembersRequest add(@jakarta.annotation.Nullable List<UUID> add) {
    
    this.add = add;
    return this;
  }

  public UpdateMembersRequest addAddItem(UUID addItem) {
    if (this.add == null) {
      this.add = new ArrayList<>();
    }
    this.add.add(addItem);
    return this;
  }

  /**
   * User ids to add to the roster.
   * @return add
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UUID> getAdd() {
    return add;
  }


  @JsonProperty(value = JSON_PROPERTY_ADD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdd(@jakarta.annotation.Nullable List<UUID> add) {
    this.add = add;
  }

  public UpdateMembersRequest remove(@jakarta.annotation.Nullable List<UUID> remove) {
    
    this.remove = remove;
    return this;
  }

  public UpdateMembersRequest addRemoveItem(UUID removeItem) {
    if (this.remove == null) {
      this.remove = new ArrayList<>();
    }
    this.remove.add(removeItem);
    return this;
  }

  /**
   * User ids to remove from the roster.
   * @return remove
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REMOVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UUID> getRemove() {
    return remove;
  }


  @JsonProperty(value = JSON_PROPERTY_REMOVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRemove(@jakarta.annotation.Nullable List<UUID> remove) {
    this.remove = remove;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateMembersRequest updateMembersRequest = (UpdateMembersRequest) o;
    return Objects.equals(this.add, updateMembersRequest.add) &&
        Objects.equals(this.remove, updateMembersRequest.remove);
  }

  @Override
  public int hashCode() {
    return Objects.hash(add, remove);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateMembersRequest {\n");
    sb.append("    add: ").append(toIndentedString(add)).append("\n");
    sb.append("    remove: ").append(toIndentedString(remove)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

