/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.fourletters.dto.PublicUser;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Public profiles for a batch of requested user ids. Missing/unknown ids are simply omitted.
 */
@JsonPropertyOrder({
  UserBatchResponse.JSON_PROPERTY_USERS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class UserBatchResponse {
  public static final String JSON_PROPERTY_USERS = "users";
  @jakarta.annotation.Nonnull
  private List<PublicUser> users = new ArrayList<>();

  public UserBatchResponse() {
  }

  public UserBatchResponse users(@jakarta.annotation.Nonnull List<PublicUser> users) {
    
    this.users = users;
    return this;
  }

  public UserBatchResponse addUsersItem(PublicUser usersItem) {
    if (this.users == null) {
      this.users = new ArrayList<>();
    }
    this.users.add(usersItem);
    return this;
  }

  /**
   * Get users
   * @return users
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<PublicUser> getUsers() {
    return users;
  }


  @JsonProperty(value = JSON_PROPERTY_USERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsers(@jakarta.annotation.Nonnull List<PublicUser> users) {
    this.users = users;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserBatchResponse userBatchResponse = (UserBatchResponse) o;
    return Objects.equals(this.users, userBatchResponse.users);
  }

  @Override
  public int hashCode() {
    return Objects.hash(users);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserBatchResponse {\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

