/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UserResponse
 */
@JsonPropertyOrder({
  UserResponse.JSON_PROPERTY_ID,
  UserResponse.JSON_PROPERTY_USERNAME,
  UserResponse.JSON_PROPERTY_AVATAR_URL,
  UserResponse.JSON_PROPERTY_ROLES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T19:09:22.768486900+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class UserResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_USERNAME = "username";
  @jakarta.annotation.Nonnull
  private String username;

  public static final String JSON_PROPERTY_AVATAR_URL = "avatarUrl";
  @jakarta.annotation.Nullable
  private URI avatarUrl;

  public static final String JSON_PROPERTY_ROLES = "roles";
  @jakarta.annotation.Nonnull
  private List<String> roles = new ArrayList<>();

  public UserResponse() {
  }

  public UserResponse id(@jakarta.annotation.Nonnull UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }

  public UserResponse username(@jakarta.annotation.Nonnull String username) {
    
    this.username = username;
    return this;
  }

  /**
   * Get username
   * @return username
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsername(@jakarta.annotation.Nonnull String username) {
    this.username = username;
  }

  public UserResponse avatarUrl(@jakarta.annotation.Nullable URI avatarUrl) {
    
    this.avatarUrl = avatarUrl;
    return this;
  }

  /**
   * Get avatarUrl
   * @return avatarUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVATAR_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getAvatarUrl() {
    return avatarUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_AVATAR_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvatarUrl(@jakarta.annotation.Nullable URI avatarUrl) {
    this.avatarUrl = avatarUrl;
  }

  public UserResponse roles(@jakarta.annotation.Nonnull List<String> roles) {
    
    this.roles = roles;
    return this;
  }

  public UserResponse addRolesItem(String rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<>();
    }
    this.roles.add(rolesItem);
    return this;
  }

  /**
   * List of user permissions/roles for RBAC.
   * @return roles
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROLES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getRoles() {
    return roles;
  }


  @JsonProperty(value = JSON_PROPERTY_ROLES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoles(@jakarta.annotation.Nonnull List<String> roles) {
    this.roles = roles;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserResponse userResponse = (UserResponse) o;
    return Objects.equals(this.id, userResponse.id) &&
        Objects.equals(this.username, userResponse.username) &&
        Objects.equals(this.avatarUrl, userResponse.avatarUrl) &&
        Objects.equals(this.roles, userResponse.roles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, username, avatarUrl, roles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

