/*
 * Shared Data Models for Fourletters API
 * Shared data models for the fourletters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.fourletters.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The group&#39;s symmetric epoch key wrapped (encrypted) to a single member&#39;s encryption public key. The Server stores and relays this opaque blob but never the group key itself.
 */
@JsonPropertyOrder({
  WrappedGroupKey.JSON_PROPERTY_RECIPIENT_ID,
  WrappedGroupKey.JSON_PROPERTY_WRAPPED_KEY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-22T14:10:45.096494+03:00[Europe/Athens]", comments = "Generator version: 7.21.0")
public class WrappedGroupKey {
  public static final String JSON_PROPERTY_RECIPIENT_ID = "recipientId";
  @jakarta.annotation.Nonnull
  private UUID recipientId;

  public static final String JSON_PROPERTY_WRAPPED_KEY = "wrappedKey";
  @jakarta.annotation.Nonnull
  private String wrappedKey;

  public WrappedGroupKey() {
  }

  public WrappedGroupKey recipientId(@jakarta.annotation.Nonnull UUID recipientId) {
    
    this.recipientId = recipientId;
    return this;
  }

  /**
   * The member this blob is encrypted for.
   * @return recipientId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECIPIENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getRecipientId() {
    return recipientId;
  }


  @JsonProperty(value = JSON_PROPERTY_RECIPIENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecipientId(@jakarta.annotation.Nonnull UUID recipientId) {
    this.recipientId = recipientId;
  }

  public WrappedGroupKey wrappedKey(@jakarta.annotation.Nonnull String wrappedKey) {
    
    this.wrappedKey = wrappedKey;
    return this;
  }

  /**
   * The group epoch key wrapped to the member&#39;s ECDH encryption key (Base64, same ephemeral-ECDH + AES-GCM envelope used for 1:1 payloads).
   * @return wrappedKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WRAPPED_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWrappedKey() {
    return wrappedKey;
  }


  @JsonProperty(value = JSON_PROPERTY_WRAPPED_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWrappedKey(@jakarta.annotation.Nonnull String wrappedKey) {
    this.wrappedKey = wrappedKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WrappedGroupKey wrappedGroupKey = (WrappedGroupKey) o;
    return Objects.equals(this.recipientId, wrappedGroupKey.recipientId) &&
        Objects.equals(this.wrappedKey, wrappedGroupKey.wrappedKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recipientId, wrappedKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WrappedGroupKey {\n");
    sb.append("    recipientId: ").append(toIndentedString(recipientId)).append("\n");
    sb.append("    wrappedKey: ").append(toIndentedString(wrappedKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

